name: Deploy API

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_REPOSITORY: estoria-sem-fim-api
  HEROKU_APP_NAME: estoria-sem-fim-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: "${DOCKER_HUB_REPOSITORY}"

    - name: Deploy to Heroku
      uses: godbold/heroku-deploy@v0.1.0
      with:
        herokuApiKey: ${{ secrets.HEROKU_API_KEY }}
        appName: "${HEROKU_APP_NAME}"
        image: "${DOCKER_HUB_REPOSITORY}"
